# lab1

this is my first lab for IA 340.

In [1]:
import pandas as pd 

covid_data = pd.read_csv('s3://ia340-2025-fall-86358/data.csv')

covid_data.head()

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/fsspec/registry.py:298: UserWarning: Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

  warnings.warn(s3_msg)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,14/12/2020,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779
1,13/12/2020,13,12,2020,298,9,Afghanistan,AF,AFG,38041757.0,Asia,7.052776
2,12/12/2020,12,12,2020,113,11,Afghanistan,AF,AFG,38041757.0,Asia,6.868768
3,11/12/2020,11,12,2020,63,10,Afghanistan,AF,AFG,38041757.0,Asia,7.134266
4,10/12/2020,10,12,2020,202,16,Afghanistan,AF,AFG,38041757.0,Asia,6.968658

In [3]:
import pandas as pd

HSHealth_data = pd.read_csv('s3://ia340-2025-fall-86358/DASH_-_Global_School-based_Student_Health_Survey__GSHS_.csv')

HSHealth_data.head()

,Year,LocationAbbr,LocationDesc,DataSource,Topic,Subtopic,ShortQuestionText,Greater_Risk_Question,Description,Data_Value_Symbol,...,Age,GeoLocation,TopicID,SubtopicID,QuestionCode,LocationId,StratID1,StratID2,StratID3,StratificationType
0,2010,NU,Niue,GSHS,Dietary Behaviors,Body Weight,Obesity,Were obese,>+2SD from the median for BMI by age and sex,%,...,13,NaN,C05,C39,QNOBESEG,NaN,S1,A2,NU,Western Pacific
1,2003,UGB,Uganda (Urban),GSHS,Dietary Behaviors,Vegetables,No vegetable consumption,Did not eat vegetables,during the 30 days before the survey,%,...,13,NaN,C05,C19,G8,NaN,S7,A2,UGB,African
2,2011,SI,Solomon Islands,GSHS,Dietary Behaviors,Fruit,Fruit consumption >= 1 time,NaN,during the 30 days before the survey,%,...,13,NaN,C05,C41,QNFR1G,NaN,S8,A2,SI,Western Pacific
3,2015,SH,Seychelles,GSHS,Mental Health,Mental Health,Close Friends,Did not have close friends,NaN,%,...,17,NaN,C36,C46,G27,NaN,S8,A6,SH,African
4,2011,SI,Solomon Islands,GSHS,Dietary Behaviors,Body Weight,Overweight,Were overweight,>+1SD from the median for BMI by age and sex,%,...,13,NaN,C05,C39,QNOWTG,NaN,S8,A2,SI,Western Pacific